### ISSUE TITLE
Error trying to process data url in css

### ISSUE THREAD

**Issue by jeffsheets** [hollandben/grunt-cache-bust#120]
We have some images as data url on background-image rules inside our css files. I would expect the cacheBust to ignore these lines. But when cacheBust is executed we get an error:

```
Warning: Cannot read property '1' of null Use --force to continue.
```

Sample CSS:
```
.data-url-image {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABp0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjUuMTAw9HKhAAAAmElEQVQoU33PQapBURjA8UtkwJuaWYGSgfQWYBMvczPmTCzAAGVuaA228BZhRCkDGSmE31FucuRfvzq3vr5zT/JSjSU7DsypEPXDkDVn2hSIytJhw4kWGaLCxgHh2gt/RBuLzNhz5caWPjnSqqw4EraFfwznf8qklWjwy4IRTerkiQoPGtPl40OehcEJvcfXl8LglLfBJLkDcMgbgHlHhK8AAAAASUVORK5CYII=);
}
```

You can see the behavior by pasting this .data-url-image to the bottom of tests/stylesheets/stylesheet.css and running the tests.

**Comment by hollandben** [comment]
Fixed and pushed to NPM. New version is `0.4.11`

**Comment by jeffsheets** [comment]
Wow fixed in less than 1 hour, amazing!

I pulled in 0.4.11 and it works great
