### ISSUE TITLE
deleteOriginals does not honor baseDir

### ISSUE THREAD

**Issue by eatrocks** [hollandben/grunt-cache-bust#122]
Version 0.4.10 of cache bust, which I do not see here on github, strange, deletes my app.js which exists one directory above the baseDir instead of deleting the app.js in the baseDir.
I do not see this behavior in 0.4.4 and did not test any other versions.

**Comment by hollandben** [comment]
Can you share your config with me and basic file structure - that would help a bit more.

FYI, the master branch of the repo is currently `0.4.11` and is usually equal to what is on NPM.

**Comment by hollandben** [comment]
Just figured out what you meant and yes, this functionality does seem to be broken. I will create a test case for it now and publish the fix

**Comment by hollandben** [comment]
I've merged a fix and publish to npm again. New version is `0.4.12`.

Thanks for letting me know of the bug

**Comment by eatrocks** [comment]
You are welcome. Thanks for fixing it, especially so fast. I just tested
and it is fixed in 0.4.12.
thanks again,
Bruce
