### ISSUE TITLE
cannot read property failure for @font-face

### ISSUE THREAD

**Issue by mbenna** [hollandben/grunt-cache-bust#128]
I have this code:

    @font-face {
      src: local('Lato-Hairline'), url(https://fonts.gstatic.com/s/lato/v11/zJY4gsxBiSo5L7tNutxFNg.ttf);
    }

Which produces this error:

    Warning: Cannot read property '1' of null Use --force to continue.
    Aborted due to warnings.

I've tried quotes around the URI but it did not change the outcome. Any ideas?

On a related topic, a src file and line number for the error would make narrowing it down much easier :)

**Comment by hollandben** [comment]
I need to add a small change so that it filters out remote assets when parsing CSS.

And yep, error messages need to be a lot better! :)

**Comment by mbenna** [comment]
Fast fix! At least I had time to sleep between reporting and confirming fix. :)

Fix confirmed. Thanks.

**Comment by hollandben** [comment]
Haha the joys of me being ~7 hours difference
