### ISSUE TITLE
Rename option without file existence checking

### ISSUE THREAD

**Issue by junajan** [hollandben/grunt-cache-bust#136]
Hi,
if I specify in options "rename: false", it should only append hash to file path or as GET parameter?
Is it necessary to test if files exist then? 

I have dist folder, where an application is assembled and after it's finished it is cacheBusted and moved to /app/ folder. So all my urls start with /app/, files are in /dist/ folder and grunt-cache-bust looks for them in /dist/app/... which ends with "Unable to read" error.

**Comment by ansballard** [comment]
The file is needed because the hash is based on the file. Have you tried setting your baseDir?

```javascript
cacheBust: {
  options: {
    baseDir: "dist/" // it may be "/dist/"
  }
  ...
}
```

**Comment by junajan** [comment]
I think so.. (but not 100% sure)
At the end, I just created subdir app where is an app builded.. 

I will close this issue for now because original problem is solved..
