### ISSUE TITLE
Cache bust with php view files

### ISSUE THREAD

**Issue by carlotrimarchi** [hollandben/grunt-cache-bust#138]
Hi,
is there any way I can use this task in a php project?
I'm working on Codeigniter, so all the html code is inside php view files.

Thanks for your help

**Comment by hollandben** [comment]
Hi @carlotrimarchi - could you provide me with an example? There's the `enableUrlFragmentHint` option which may provide some help. You can see [an example here](https://github.com/hollandben/grunt-cache-bust/blob/master/tests/enableUrlFragments/enableUrlFragments.php)

**Comment by carlotrimarchi** [comment]
thanks for the reply, @hollandben, and sorry for my late reply now. The enableUrlFragmentHit was all I needed, but I didn't understand it from the docs.

Thank you!
