### ISSUE TITLE
grunt-cache-bust hashes can not be validated

### ISSUE THREAD

**Issue by thrawn-sh** [hollandben/grunt-cache-bust#142]
I'm using grunt-cache-bust to generate md5 hashes for all my assets. These hashes can not be validated, as they differ for binary files (like images or fonts) from the calculated hash sum of every other tool.

**Comment by hollandben** [comment]
This should [be fixed now](https://github.com/hollandben/grunt-cache-bust/commit/d4f863d9f9dee31112679cfd723ba5b3d4167881) - thanks for bringing it up.
