### ISSUE TITLE
resourses in javascript are not processed

### ISSUE THREAD

**Issue by thrawn-sh** [hollandben/grunt-cache-bust#144]
I'm using angular template caches for my project please see the content and syntax of template.js below:

```javascript
angular.module('test').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('main/home.html',
    "<ul class=\"slides\"><li><img src=\"images/home-01.jpg\" alt=\"\"></li><li><img src=\"images/home-02.jpg\" alt=\"\"></li></ul>"
  );
}]);
```

The template cache contains 2 image assets home-01.jpg and home-02.jpg. both resources are not process at all by grunt-cache-bust, they are not renamed in the filesystem nor in the template.js

```javascript
cacheBust: {
            options: {
                algorithm: "md5",
                deleteOriginals: true,
                ignorePatterns: ["android-chrome", "apple-touch-icon", "favicon"],
                length: 32,
                removeUrlFragmentHint: true,
                rename: true,
            },
            assets: {
                files: [
                    { src: ["dist/**/*.css"] , filter: "isFile" },
                    { src: ["dist/**/*.js"]  , filter: "isFile" },
                    { src: ["dist/**/*.html"], filter: "isFile" },
                ],
            },
},
```

**Comment by hollandben** [comment]
I'm going to be re-writing the way the plugin works for `v1.0.0` so hang tight - it'll be much easier to use and account for features such as this

**Comment by jdat82** [comment]
+1 for this feature. Thanks for your awesome plugin.

**Comment by hollandben** [comment]
@thrawn-sh, @jdat82 would you be able to try out the current implementation on `feature/v1.0.0-beta` to see if this works for you (it should). You can read more about the changes in #147

**Comment by thrawn-sh** [comment]
Did a quick check, seems to work.
