### ISSUE TITLE
No bust for: SVG <use> xlink:href, and apple-touch-icons

### ISSUE THREAD

**Issue by JamesJosephFinn** [hollandben/grunt-cache-bust#149]
All other static assets get busted as advertised. Your changelog states that as of v. 0.4.2 something like this should work: `<use xlink:href="img/symbol/svg/sprite.symbol.svg#logo"></use>`, but no go for me. This feature would be nice.

Also, and this is not that important to me, but for some reason I can't figure, these don't get busted either: `link rel="apple-touch-icon"`. This issue is not as important as `svg use`, just curious.

I love the plug-in otherwise. Thank you!

**Comment by hollandben** [comment]
Hi James - have a look at using the `v1.0.0-beta` branch as this will work in that branch. I'll be merging this branch soon once a few people have tested it out. Thanks

**Comment by hollandben** [comment]
Working in `feature/v1.0.0-beta` branch
