### ISSUE TITLE
Running grunt instance will not necessarily be used when registering cacheBust

### ISSUE THREAD

**Issue by dnagoda** [hollandben/grunt-cache-bust#151]
I'm currently working on a project to encapsulate the common portions of our grunt projects into a node module that we can use as a dependency in other projects. Using load-grunt-config and grunt-jit we can merge configs/plugins from the common project and the dependent project, reducing a lot of copying.

The result is a project structure like this:

* dependent_project/
  * node_modules/
    * common_grunt_project/
      * node_modules/
        * grunt-cache-bust

where I can call grunt tasks defined in the common_grunt_project from the dependent_project.

I'm running into a problem where if grunt-cache-bust is defined as a common_grunt_project task, it gets registered on a different instance of grunt than all the rest of the tasks. I think the problem is how cachebust.js requires grunt and then registers itself. In that code the module.exports function doesn't use the grunt instance that is passed in, instead the grunt instance required at the top of the file is used. In a project setup like I've described above this will mean a different instance is used.

I understand that this is potentially an edge case, but the fix would be to change the module.exports line back to:

``module.exports = function(grunt)``

I'll work on a patch.

**Comment by hollandben** [comment]
Fixed in #152
