### ISSUE TITLE
How to make update only changed files?

### ISSUE THREAD

**Issue by 2ge** [hollandben/grunt-cache-bust#158]
Hi all,

when I am deploying to server using rsync from my dev server and running before cache-bust, same files are uploaded to server again and again. Is there some workaround for this to write files, only when they are unique (update was made) ? 

Thanks

```
	 	cacheBust: {
	    	options: {
	      		encoding: 'utf8',
	      		algorithm: 'md5',
	      		length: 16,
		  		deleteOriginals: false,
	      		baseDir: '/data/www/mydomain.com/public_html',		
	    	},
	    	assets: {
	        	files: [{  
					expand: true,	  			  
					cwd: 'xsl/new_design',
	            	src: ['xhtml.xsl'],
	        	}]
	    	}
	  	},
```

**Comment by hollandben** [comment]
Unfortunately not. The plugin will do a full clean run and generate all the files even if they haven't changed. It's advised be able to do a full clean build when deploying an application.
