### ISSUE TITLE
cdnPath Feature doesn´t work since 0.4.12

### ISSUE THREAD

**Issue by lietzi** [hollandben/grunt-cache-bust#160]
Hi there!

After updating from 0.4.6 to 0.6.0 the cdnPath Feature seems to be broken.
I tried to find the last "working" version: 
It is 0.4.12 
but since Version 0.4.7 the originals would not be deleted anymore.

There is a mistake in your tests - they only check if the files are ignored instead of follow this feature description:
"When set, cachebust test paths against this string when attempting to determine a path to be remote or not. This allows all assets to be busted locally and than uploaded to your own CDN. This string will be ignored in paths during file-handling to find files in baseDir."

Would be nice if you could fix this!

Cheers,
lietzi

**Comment by GFoley83** [comment]
:+1:

**Comment by zuper-tom** [comment]
i can confirm that this is indeed the case. the code is quite hard for me to follow, but here's 0.4.12 vs 0.6.0:
0.4.12: https://github.com/hollandben/grunt-cache-bust/blob/4c0bfe48baa6b11cac39a1015f76641e948433eb/tasks/cachebust.js#L115
0.6.0: https://github.com/hollandben/grunt-cache-bust/blob/a9f1fdf98143b10876632462c5c1a629dfe52d26/tasks/cachebust.js#L70

maybe someone who has more insight into how this plugin works can fix this

**Comment by thedug** [comment]
+1

**Comment by hollandben** [comment]
Hello all,

Can someone be a little clearer about what the problem is? The test case currently is as follows:

- There's a resource with a prefix to the a CDN where your files will be uploaded (that's your job), i.e. `cdn.domain.com`
- You tell `grunt-cache-bust` that the CDN domain is `cdn.domain.com`
- When it finds a resource, it checks if the domain is `cdn.domain.com`. If so, it attempts to bust that file using the one on the local system
- If successful, it then updates the reference in the file leaving the `cdn.domain.com` in place

**Comment by lietzi** [comment]
Hi Ben,

the usecase for my first commit of this feature was to test against a path.. 
not only for a domain.. for example cdn.domain.com/path/to/subfolder

i use a single cdn-domain with ssl for multiple sites with subfolders..
That's why I called the option cdnPath ;)

i´m actually using the old version 0.4.12 and planing to check for the easiest solution:
changing my cdn-server structure (wildcard ssl + subdomain for each site or routing on the cdn according to request-reference) or implementing the old subfolder-routine in this plugin ;)

if you find a solution with low efforts it would be nice..
but for me it is actually not so important.. 

Thank you!

Cheers,
Lietzi

**Comment by hollandben** [comment]
Ahh ok, thanks for the clarification. It should work for your use case in the `v1.0.0` branch btw - maybe give that a try. You can read more about the changes over at #147

**Comment by lietzi** [comment]
Hi Ben,

i just tried v1.0.0-beta on a private projekt..
this issue is solved!

Cheers,
Lietzi
