### ISSUE TITLE
Can't cache bust my own CDN

### ISSUE THREAD

**Issue by GFoley83** [hollandben/grunt-cache-bust#161]
We have our own CDN in place `//cdn.mysite.com` (running on CloudFront) which get's prefixed to all css and js references in the index.html prior to running `grunt cacheBust`. As a result cacheBust ignores these files so I can't cache bust them.

Is there any way to force cache to work on remote URLs? Of even better and a option to prefix references with a string, e.g. my CDN URL?

**Comment by thedug** [comment]
@GFoley83 Did you find a work around?

**Comment by hollandben** [comment]
Hi,

Cache busting and uploading to your own CDN is already supported. Have a look at the [cdnPath option](https://github.com/hollandben/grunt-cache-bust#optionscdnpath). If that's not working for you, let me know and we'll try to figure something out

**Comment by hollandben** [comment]
This should now work fine with the version `1.x.x`
