### ISSUE TITLE
Workflow to cache bust images

### ISSUE THREAD

**Issue by carlotrimarchi** [hollandben/grunt-cache-bust#164]
Hi,
it's not completely clear to me how use the task with static images.

I have this configuration:
```
cacheBust: {
            options: {
                encoding: 'utf8',
                algorithm: 'md5',
                length: 16,
                deleteOriginals: true,
                enableUrlFragmentHint: true
            },
            assets: {
                files: [{
                    baseDir: './',
                    src: ['application/views/**/*.php']
                }]
            }
        }
```

And it works. Even withouth putting the `UrlFragmentHint` it correctly finds images in the code and adds the hashcode to them. It also deletes the original files, which, maybe, in the case of images is not good.
Now when I run the task I get messages like:

`Static asset "public/assets/images/mail_banner_gmail.png" skipped because it wasn't found, original reference=public/assets/images/mail_banner_gmail.a0ebd52973353b65.png`

The file is actually present in the correct directory. Is this just because I'm not keeping the original images?

**Comment by hollandben** [comment]
Hi,

That seems to be the case. `deleteOriginals: true` will do what it says on the tin and delete the original files after it's been busted. Set that to `false` and let me know if that fixes it
