### ISSUE TITLE
How to make work with JSP EL expression

### ISSUE THREAD

**Issue by spshukla** [hollandben/grunt-cache-bust#167]
We are hosting our static resources over CDN, so all our static resources URL get prefixed by CDN url.

We are using JSP, so our static resources like

<link href="${static_file_path}/abc/css/similar.css" rel="stylesheet" type="text/css">

Obviously, cache burst wont be able to resolve the JSP EL. So, how do I configure cache burst to burst these resources.

**Comment by hollandben** [comment]
Hi @spshukla,

Was there meant to be a code example in this issue? Sounds like an easy thing to fix, just need to see an example

**Comment by spshukla** [comment]
We map our static assets to CDN (Cloudfront) url, so in our JSPs any static resource is represented like this

Hi @hollandben 
<img src="${cdn_url_path}/test/images/abc.jpg"/>

Lets suppose ${cdn_url_path}=http://cdnurl.aws.com

This CDN url is mapped to our LB IP, that LB in turn sends the request to our application web servers.

So, while using your plugin this JSP EL expression needs to be mapped with our context root folder, so that those files could be found and perform cache bursting accordingly.

Please let me know for any more info.

**Comment by hollandben** [comment]
Ahh ok. You could probably get away with setting the `cdnPath` option to be `${cdn_url_path}`. Don't see why that shouldn't work.

**Comment by spshukla** [comment]
@hollandben 

Please find the logs and verify the configuration.

Inside "web" folder contains all the JSPs, CSS in folders (project wise)

Got error message like this whilc running grunt task---
Static asset "web/${static_file_path}/common/css/commonHeader_SS_L_7.css" skipped because it wasn't found, original reference=$%7Bstatic_file_path%7D/common/css/commonHeader_SS_L_7.css

Confguration in Grunt JS:--
 cacheBust: {
    options: {
      encoding: 'utf8',
      algorithm: 'md5',
      length: 16,
      jsonOutput: true,
      cdnPath: '${static_file_path}'
    },
    assets: {
        files: [{
                baseDir : 'web/',
                src: ['web/**/*.*']
        }]
    }
  }

**Comment by spshukla** [comment]
@hollandben  Please help with this.

**Comment by hollandben** [comment]
I've had deeper look into the code and the original suggestion unfortunately won't work. The other option I can see will be to use the `replaceTerms` option, but that will actually replace `${cdn_url_path}` with the path that you give it - could read the config file where that's stored into your Gruntfile.

**Comment by hollandben** [comment]
Appears the be the resolution as #161 - should work in `1.x.x`
