### ISSUE TITLE
Same Cache busted string

### ISSUE THREAD

**Issue by CCSS-Github** [hollandben/grunt-cache-bust#168]
After each attempt to execute this Cache busting task it replace same string in files, so no use for me in this case. It must be unique after each execution

**Comment by hollandben** [comment]
The hash that is appended to the file name is generated based on the contents of the file. If the file doesn't change, then the hash won't change. Out of interest, why would you want the hash to be unique every time?

**Comment by hollandben** [comment]
Closing as the way files are hashed won't be changed going forward
