### ISSUE TITLE
Busting files referenced within RequireJS

### ISSUE THREAD

**Issue by matthewtrinder** [hollandben/grunt-cache-bust#171]
I've just started trying out grunt-cache-bust and although I've been successful in getting it to trawl html and css files for references I'm struggling to bust files that are referenced within requirejs - which is unfortunately most of my javascript...

Would really appreciate any help anyone can offer on this, also is this even something grunt-cache-bust is capable of?! Or am I asking for too much?

### References to require.js and it's target script are being busted correctly

    <script async src="/assets/js/third-party/require.5fbbb370a8f3d5fc.js" data-main="/assets/js/require/default.946400fe39e8987c.js"></script>

### However I can't figure out how to target files referenced within require itself (which don't even have full paths or extensions listed), e.g:

**default.js:**
```
    requirejs(['./config', './common']);
```
**config.js:**
```
    requirejs.config({
        "baseUrl": "/assets/js/",
        "paths": {
          "jquery": "third-party/jquery",
          "modernizr": "third-party/modernizr",
          "loadCSS": "third-party/loadCSS"
        }
    });
```

**common.js:**
(jquery and loadCSS are reference to **/assets/js/third-party/jquery.js** and **/assets/js/third-party/loadCSS.js** but these are paths are aliased in the config above. The script executed when loadCSS has been fetched contains some full URLs which need to be busted also).

```
    requirejs(['jquery'], function() {
        // Some jquery stuff would happen here...
    });
    requirejs(['loadCSS'], function() {
        loadCSS("/assets/css/main.css");
        loadCSS("//fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic,900,900italic");
    });
```
### Here's my grunt-cache-bust config thus far:

```
module.exports = {
    options: {
        encoding: 'utf8',
        algorithm: 'md5',
        length: 16,
        deleteOriginals: true,
        baseDir: 'build/production/',
        filters: {
            'script': [
                function() {
                    return this.attribs['data-main'];
                }, // for requirejs mains.js
                function() {
                    return this.attribs.src;
                }
            ]
        }
    },
    assets: {
        files: [{
            expand: true,
            cwd: 'build/production',
            src: [
                'assets/css/*.css',
                'assets/js/*.js',
                '*.html'
            ],
            dest: ''
        }]
    }
}
```

Once again, any help would be hugely appreciated! As other than this particular stumbling block, everything else has worked really well.

**Comment by hollandben** [comment]
Hi @matthewtrinder.

Are you not using the optimiser that comes with RequireJS to concatenate all these files into one bundle?

I'm not sure how we'll be able to cache bust each individual file especially with the relative paths that require uses, but we may be able to work something out.

**Comment by hollandben** [comment]
Closing as it's become stale. If anyone else would like to try getting this to work with RequireJS then I'm happy to assist
