### ISSUE TITLE
ignore certain asset references

### ISSUE THREAD

**Issue by thedug** [hollandben/grunt-cache-bust#172]
Is it possible to skip certain asset references.

In this case the src attribute is a bind variable that will have a cache-busted url. So I don't need to replace.

>> Static asset "app/media/{{art.image}}" skipped because it wasn't found, original reference=%7B%7Bart.image%7D%7D

**Comment by hollandben** [comment]
That's just a warning message - it should skip this asset as it can't be found. Is it causing you problems?

**Comment by hollandben** [comment]
You can use the `ignorePatterns` option to ignore any files that have `{{` or `}}` in them
