### ISSUE TITLE
Is it possible to update links in a file that should be busted - v1.0?

### ISSUE THREAD

**Issue by lietzi** [hollandben/grunt-cache-bust#173]
Hi Ben,

as i already mentioned in my previous issue, i tested the v1.0.0-beta..
Now i have a bunch of new issues ;) :

Is it possible to update links in a file that should be busted?

In my index.html there is a link to main.css, which i want to get busted as an asset,
but this css-file contains links to other assets, that should get busted too..

when i add the css-file to both arrays 

assets in options => to be busted 
AND 
files => to be parsed for links to busted assets

the css file could not be opened (Error code: ENOENT) ... 
at this time it is already busted and the filename has changed..

When it is only in the list "to be busted", the links to the other busted files won't get updated..
And when it is in the list to be processed, the links are ok but the css itself isnt busted..

How can i achieve this properly?

My actual config - here the css-file is not found:

```javascript
      cacheBust: {
        options: {
          baseDir: '<%= grunt.config.get("output_path")%>',
          deleteOriginals: true,
          assets: ['css/*','js/*','img/*','fonts/*']
        },
        assets: {
          files: [{
            expand: true,
            cwd: '<%= grunt.config.get("output_path")%>',
            src: ['css/*.css','index/*.html']
          }]
        }
      },
```

My first idea were those changes to /task/cachebust.js on lines 43ff:

```javascript
        // Go through each source file and replace terms
        // Check if filepath is in assetMap => then use busted filepath
        this.files.forEach(function (file) {
            file.src.forEach(function (filepath){
              var relativeFilepath = filepath.replace(opts.baseDir + '/','');
              if (relativeFilepath in assetMap) {
                replaceInFile(opts.baseDir + '/' + assetMap[relativeFilepath]);
              } else {
                replaceInFile(filepath);
              }
            });
        });
```

It passes all Tests and works as expected.. but it feels dirty to me.. 
so please excuse the missing pull request..

Furthermore two problems with the docs..

1. the array in options/assets isn't mentioned in the docs..
i found it in the test-configs.. but for other beta-testers it might be helpfull..

2. in the test-configs there are only two properties..
"options" and "files"..

but when i use it this way, it does not work:
This example produces "pattern.indexOf is not a function":

```javascript
      cacheBust: {
        options: {
          baseDir: '<%= grunt.config.get("output_path")%>',
          deleteOriginals: true,
          assets: ['js/*','img/*','fonts/*']
        },
        files: [{
          expand: true,
          cwd: '<%= grunt.config.get("output_path")%>',
          src: ['css/*.css','index/*.html']
        }]
      },
```
Do you have a hint for me?

Thx!

By the way: Thank you for this great Plugin!!

Cheers,
Lietzi

**Comment by hollandben** [comment]
Hello again! Thanks for trying it out - I need more people to give it a go before I push it out. I'll have a read through this later :+1:

**Comment by lietzi** [comment]
ok - i'll try it on a dev-branch of one of 
my bigger commercial projects next week..

**Comment by hollandben** [comment]
Hey - so I've had a chance to look into the problem. The order of execution was something along the lines of this:

> Find all assets => copy and hash them => go through files and replace

The problem is that the `copy and hash them` phase is creating new files which aren't in the array of files returned in the first step, `Find all assets`. I've changed the order of execution to be:

> Find all assets => copy and hash them => pickup any new files => go through files and replace

I've added a test case and pushed the changes to the branch so should be working

**Comment by lietzi** [comment]
Hi Ben,

much cleaner approach - for me it works fine.. Great Work!

But i have to reopen #148 - woff and woff2 files getting both the hash of the woff file..

Cheers,
Lietzi
