### ISSUE TITLE
Cannot read property indexOf undefined

### ISSUE THREAD

**Issue by devotox** [hollandben/grunt-cache-bust#184]
```
Running "cacheBust:assets" (cacheBust) task
Warning: Cannot read property 'indexOf' of undefined Use --force to continue.
```

Error i get trying to cachebust

**Comment by devotox** [comment]
```

		cacheBust: {
			options: {
				length: 16,
				rename: false,
				encoding: 'utf8',
				algorithm: 'md5',
				deleteOriginals: false,
				ignorePatterns: ['controllers','directives','services',
								 'dynamic-live-reload', 'jquery-extensions',
								 'lodash-extensions', 'request-animation-frame',
								 'bower_components', 'assets', 'favicon', 'icon' ]
			},
			assets: {
				files: [{
					src: ['<%= pkg.assetPath %>index.html']
				}]
			}
		},
```

and package.assetPath does go to the right folder as it is what i am using for my other grunt tasks

This is on the latest version 1.1.1 btw

**Comment by hollandben** [comment]
Have a read of the documentation as the way the plugin works and the way it should be used has changed, hence the bump to version `1`.

In short, you need to give it the folder of where your assets are using the `assets` option. It will only replace references to those assets in the given src files. Your conifg should look more like this:

```javascript
cacheBust: {
    options: {
        length: 16,
        rename: false,
        encoding: 'utf8',
        algorithm: 'md5',
        deleteOriginals: false,
        assets: ['./path/to/assets/on/file/system/**/*']
    },
    assets: {
        src: ['<%= pkg.assetPath %>index.html']
    }
}
```

**Comment by devotox** [comment]
Ha soo you do not do the query string way anymore? you only use the full file replacement?

**Comment by hollandben** [comment]
Yep, that's correct

**Comment by devotox** [comment]
thank you. I will close this now. Can i just ask why you decided to take of URL querystring as it was best for my usage where the files can come from any of five servers and if it uses a different filename this would not be the same on each of the servers and thus cause a 404 at any point?

**Comment by hollandben** [comment]
Some CDN's strip away the query string for a filename, as can some browsers/devices, meaning that you aren't always guaranteed to be serving fresh files to users. Although there is a small chance of this happening, it's seen as better practice to rename the file completely, leaving no doubt that you are serving the latest file to the user.

What does your deployment pipeline look like at the moment? Does the application get packaged up and sent to all five servers or does each server build the application itself during deployment? Either way, the filename should be consist across all servers as the hash of the file should be the same, so I can't see how it would cause a problem?

**Comment by devotox** [comment]
the server builds the application each time and the previous time i tried doing it the way that is default now it created different hashes each time for each server

**Comment by hollandben** [comment]
That may well have been a bug with a previous version as it was reported a few times (i.e. #134). It'd be worth trying it again

**Comment by devotox** [comment]
Alright will do. Thank you again you have been very helpful

**Comment by hollandben** [comment]
No problem. Doctify looks really cool btw - let me know if you need anymore help/advice on things
