### ISSUE TITLE
Running Grunt is not changing the old query string in index.html

### ISSUE THREAD

**Issue by hentry** [hollandben/grunt-cache-bust#187]
I am using the query string mechanism to bust the cache. Following is the snippet in my gruntFile.js
```
cacheBust: {
            taskName: {
                options: {
                    assets: ['app/**', 'assets/css/*', 'js/*', 'build/*', 'bower_components/**'],
                    queryString : true
                },
                src: ['index.html']
            }
        }
```

For the first time, when i run grunt then the query string is attached to each scource files in script tag like,
`<script src="bower_components/jquery/dist/jquery.min.js?4a356126b9573eb7"></script>`

**But, if I run grunt again, the query string is not changed. **

**Comment by hollandben** [comment]
I'm assuming you are using the latest version?

Have a read through the discussion in #180 - should give you some insight as to why

**Comment by Instagit** [comment]
I have the same issue. As you suggested in #180, I clean the target directory, copy the files and then process them, but when the files already have a hash in the name, the index file is not updated at all and points to non-existing files. Only when I remove the hash part, i.e.

style.34f39e34ac32.css -> style.css

the file is correctly updated with the new hash.

Settings are:

```
cacheBust: {
  taskName: {
    options: {
      assets: [
        'dist/css/*.css',
        'dist/js/*.js'
      ]
    },
    src: ['index.html']
  }
}
```

**Comment by hollandben** [comment]
This is expected behaviour. The reason for copying your source files to another directory to do the processing is that the source files stay intact and are modified with the hashed value.

```html
<!-- src/index.html -->
<link rel="stylesheet" href="style.css">
```

    copy files to `dist/` folder and run the cache bust task

```html
<!-- dist/index.html -->
<link rel="stylesheet" href="style.34f39e34ac32.css">
```

The `dist/index.html` file is the one that should be deployed to your production environment. It should not be copied back to the `src/` folder. This way, on the next build/deployment, it will be changing the `style.css` file to `style.34f39e34ac32.css` again

**Comment by Instagit** [comment]
That makes sense. I was expecting it to change the index file in place. Sorry and thanks for your time.

**Comment by flaurian** [comment]
I am using grunt build to create the dist folder to be deployed.
Gruntfile file has following code 
`cacheBust: {
           taskName: {
            options: {
                assets: ['dist/client/app/vendor.js']
            },
            src: ['dist/client/index.html']
        }
    }`

The vendor file gets copied and renamed vendor.0535875986f49276.js but the html file still points to vendor.js

`<script src="app/vendor.js"></script>`

What am I doing wrong?

**Comment by hollandben** [comment]
Hi @flaurian, looks like you're missing the `baseDir` option. The file path shown in the output of your task should be something along the lines of:

    Busted: dist/client/app/vendor.0535875986f49276.js

This means it will try to replace any reference of `dist/client/app/vendor.js` with `dist/client/app/vendor.0535875986f49276.js`, but from the snippet you've provided, the reference is `app/vendor.js`.

What we need to do is remove the `dist/clients` prefix from the references which can be done by setting a `baseDir`.

```javascript
cacheBust: {
    taskName: {
        options: {
            baseDir: 'dist/client/',
            assets: ['app/vendor.js']
        },
        src: ['dist/client/index.html']
    }
}
```

This will mean that all references to assets are relative to the `dist/client/` path

**Comment by flaurian** [comment]
Thanks a lot for your quick reply. 
It works like a charm!

**Comment by MaqSaid** [comment]
Can grunt-cache-bust take source index.chtml instead of  index.html. Previously it does not seems to work.
