### ISSUE TITLE
Cache bust of partial URLs not working

### ISSUE THREAD

**Issue by Lumbendil** [hollandben/grunt-cache-bust#189]
I currently have the following task defined:

        cacheBust: {
            build: {
                options: {
                    baseDir: 'build',
                    assets: ['**'],
                    queryString: true
                },
                files: [
                    {expand: true, src: ['build/**/*'], filter: 'isFile'}
                ]
            }
        }

I also have the following file structure.

```
build
`-- desktop
    `-- css
        |-- estilos.css
        `-- images
            `-- sprite.png
```

on `estilos.css`, I have the following line of CSS: `.sprite{background:url("images/sprite.png");}`. To my understanding, this should be changed by the library to `.sprite{background:url("images/sprite.png?SOMEQUERYSTRING");}`but at the moment that is not working.

Is there anything wrong in my config, or it should be working but it isn't?

I have checked and in `cachebust.json` I can find that the sprite is indeed read, so I guess it's something to do with the fact that it's in a nested directory?

**Comment by hollandben** [comment]
Have a read through the comments in #180 and #183

**Comment by vinaynb** [comment]
Facing the same issue. Went through #180 and #183 but still it doesn't help.

**Comment by vinaynb** [comment]
Ok i solved it. I was missing the baseDir parameter due to which the paths in my index.html did not change.
