### ISSUE TITLE
Question: can I cache bust resources when using c:url

### ISSUE THREAD

**Issue by tylersmith34** [hollandben/grunt-cache-bust#194]
I have a Java/Spring webapp and my JSPs are using the JSTL `c:url` tag inside the href attribute to import my resources files.  When I did this cache busting stopped finding the resources and busting them.  Is this plugin intended to work with this configuration and if not, is it possible to do so?

I had problems with the relative paths in my application and needed to implement c:url to prevent issues with my content not loading correctly.

**Comment by hollandben** [comment]
Hi @tylersmith34. Are you able to provide a code example of what the `c:url` tag looks like? Where do your assets live in your folder structure?

**Comment by tylersmith34** [comment]
@hollandben Sure.  Here is one of my imports:
`<link rel="stylesheet" href="<c:url value="/resources/css/actionCenter.css"/>"/>`

My structure is as follows:
`src/main/webapp/resources/js`
`src/main/webapp/resources/css`
`src/main/webapp/WEB-INF/views` (my JSPs are under here)

**Comment by hollandben** [comment]
Can you provide your current `grunt-cache-bust` configuration as well.

Looks like it should work fine with the right configuration - what version of the plugin are you using?

**Comment by tylersmith34** [comment]
I realized this project wasn't on the latest version.  I upgraded and it is working.  I am working with another legacy system that was on the latest version and it too wasn't working.  After your comment I looked at that project again and found this:

`<link rel="stylesheet" type="text/css" href='<c:url value='/CSS/dialogs/dialog.css'/>'/>`

I changed from single quotes to double quotes and busting worked as advertised!
`<link rel="stylesheet" type="text/css" href="<c:url value="/CSS/dialogs/dialog.css"/>"/>`

Thank you very much for your time and looking into this.
