### ISSUE TITLE
new query string keeps getting added instead of replacing the existing one

### ISSUE THREAD

**Issue by wazZzif** [hollandben/grunt-cache-bust#197]
Hi,

I've noticed, after each cache bust the query string gets added to the overall src instead of replacing the existing query string. Is this the intended behaviour? I recall older versions not doing this.

I am using "grunt-cache-bust" version 1.2.0.

In the example below you'll notice that there are 5 query strings:
`<script src="/js/app.ng.min.js?43f14a1b434a9cb1?eb4f7c79de98ec9d?43f14a1b434a9cb1?b8051b6fbe59fbcf?f14d6f11c0365703"></script>`

I've tried various settings, here are some examples:

_cacheBust: {
all: {
                options: {
                    encoding: "utf8",
                    algorithm: "md5",
                    length: 16,
                    rename: false,
                    queryString: true,
                    baseDir: "app/",
                    assets: ["js/*", "css/*"]
                },
                src: ["app/index.html"]
            },
            js: {
                options: {
                    //encoding: "utf8",
                    //algorithm: "md5",
                    //length: 16,
                    //rename: false,
                    queryString: true,
                    baseDir: "app/",
                    assets: ["js/*"],
                    createCopies: false
                },
                src: ["app/index.html"]
            },
            css: {
                options: {
                    //encoding: "utf8",
                    //algorithm: "md5",
                    //length: 16,
                    //rename: false,
                    //queryString: true,
                    baseDir: "app/",
                    assets: ["css/*"]
                },
                src: ["app/index.html"]
            }
        },_

**Comment by hollandben** [comment]
Hi @wazZzif. Please read through the comments in #180.

Closing as it's a duplicate
