### ISSUE TITLE
replace file paths in files that exist in outputDir i.e. css and js

### ISSUE THREAD

**Issue by glhewett** [hollandben/grunt-cache-bust#209]
I have a project that I am working on that I would like to use the the outputDir.  My project is a fairly standard single page application.  The CSS and JS contain paths that need to be rewritten, but when using the outputDir, the original assets are rewritten instead of the assets that are hashed and copied to the outputDir.

**Comment by glhewett** [comment]
I created a test for the bug. You can see it in my fork.

https://github.com/glhewett/grunt-cache-bust/blob/issue209/tests/outputDir/outputDir_test.js

**Comment by bytesnipe** [comment]
I don't think this applies to when only the ouputDir is used. I tried it today without using outputDir and had the same issue. It would update the unhashed one, but not the hashed one.

**Comment by glhewett** [comment]
@bytesnipe Did you try my PR?

**Comment by bytesnipe** [comment]
No, it didn't but I'm far from a grunt or javascript expert. I did notice in your changes that you have 

if (!opts.queryString && **opts.outputDir** && _.has(assetMap, file)) 

I removed that check for opts.outputDir and it didn't update the hashed file still. I haven't had time to look into it much yet.

FYI, my cacheBust config looks like this:

    cacheBust: {
        taskName: {
            options: {
                assets: [
                    'assets/**/*.html', 
                    'assets/**/*.js',
                    'assets/**/*.json',
                    'assets/**/*.css',
                    'build/**/*.html', 
                    'build/**/*.js',
                    'build/**/*.json',
                    'js/**/*.js',
                    'json/**/*.json',
                    'shared_components/**/*.html', 
                    'shared_components/**/*.js',
                    'shared_components/**/*.json'],
                baseDir: '<%= war_contents_path %>/',
                jsonOutput: true,
                jsonOutputFilename: '<%= cache_bust_json %>'
            },
            src: [
                '<%= war_contents_path %>/index.html',
                '<%= war_contents_path %>/loader.js',
                '<%= war_contents_path %>/js/LT2-IS.min.js',
                '<%= war_contents_path %>/js/LT2-IS.min.js.map']
        }
    },

**Comment by glhewett** [comment]
Thanks for taking a look.

**Comment by bytesnipe** [comment]
I think I see why it didn't work for me.

My build structure is something like this:

build
    / Gruntfile.js
dist
   / war_contents
       /assets
...

The dist folder is created during the build and files are copied into it.  So, the result is the asset map looks like this:

'assets/is.min.js': 'assets/is.min.241412343.js'

but the file variable within the operation for busting src files doesn't have the same relative paths. Instead, it looks like

../dist/war_contents/is.min.js

So the result is the file will never be found in the map.  

I'm continuing to look at it...

**Comment by bytesnipe** [comment]
Here's my fix to the above within the cachebust.js file

        function hashFile(obj, file) {
            var absPath = path.resolve(opts.baseDir, file);
            var hash = generateFileHash(grunt.file.read(absPath, {
                encoding: null
            }));
            var newFilename = addFileHash(file, hash, opts.separator);

            if (!opts.queryString) {
                if (opts.createCopies) {
                    grunt.file.copy(absPath, path.resolve(opts.baseDir, newFilename));
                }

                if (opts.deleteOriginals) {
                    grunt.file.delete(absPath);
                }
            }

            obj[file] = newFilename;

            return obj;
        }

**Comment by bytesnipe** [comment]
Here's my update to your changes within cachebust.js. After this, it works as I expect it to.

        function getFilesToBeRenamed(assetMap, files) {
            var originalConfig = files[0].orig;

            return grunt.file
                .expand(originalConfig, originalConfig.src)
                .map(function (file) {
                    
                    var obj = assetMap[file];
                    
                    // if the baseDir option is provided, the assetMap will not have
                    // the baseDir in the file path but the file we're looking for in the
                    // map will. So we have to remove that baseDir from the file during 
                    // the lookup
                    var fileKey = file;
                    if (opts.baseDir){
                        fileKey = fileKey.replace(opts.baseDir, '');
                    }
                    
                    if (!opts.queryString && _.has(assetMap, fileKey)) {
                        
                        if(opts.baseDir){
                            file = opts.baseDir + assetMap[fileKey]; 
                        }
                        else {
                            file = assetMap[fileKey];                            
                        }
                    }
                    
                    grunt.log.ok('Busted:', file);
                    return path.resolve((originalConfig.cwd ? originalConfig.cwd + path.sep : '') + file);
                });
        }
