### ISSUE TITLE
Can the script work with relative paths?

### ISSUE THREAD

**Issue by jrutter** [hollandben/grunt-cache-bust#25]
Here is my issue, in my JSP file where I need to add the cache busting - the JS includes are pointing to the relative path:

<script src="/include/js/lib/jquery/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/include/js/plugins/jquery-migrate-1.2.1.min.js"></script>

But the script will only work if I put in the full absolute path:
<script src="../../../include/js/lib/jquery/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="../../../include/js/plugins/jquery-migrate-1.2.1.min.js"></script>

Is there any way around this?

**Comment by hollandben** [comment]
This should have been fixed in #108
