### ISSUE TITLE
The Regex in L114 doesn't work as expected

### ISSUE THREAD

**Issue by yu521088** [hollandben/grunt-cache-bust#74]
```
'<!–[if lte IE 8]><script type="text/javascript" src="/lib/respond.js"></script><![endif]–>'
  .replace(/\[.*\]>|<!\[endif\]/g, '')
```
we expect it out put `<script type="text/javascript" src="/lib/respond.js"></script>`, but in fact, it will output `<!–<script type="text/javascript" src="/lib/respond.js"></script>–>`

I think the regex should be `/<!-\[.*\]>|<!\[endif\]->/g`

**Comment by hollandben** [comment]
Is this still a problem or can I close this?

**Comment by hollandben** [comment]
Closing until reported again
