### ISSUE TITLE
Feature Requets

### ISSUE THREAD

**Issue by garyrozanc** [hollandben/grunt-cache-bust#79]
Is it possible to add the feature of removing the old hashed file after a new one is created? Also, can you add a configuration option to select what you want hashed: .jpg, .png, .js, .css? You may not want to version images automatically.

**Comment by hollandben** [comment]
**Removing the previous hashed version**
We could definitively have an option to remove a previously hashed file on the system, but only when the task encounters a previously hashed reference. I'll create a separate issue for that.

Saying that, you should really be handling the cleaning and re-building of assets better, i.e. exporting the application to a `dist` folder and running tasks against that - the option shouldn't really be needed. I understand that this isn't possible in all projects though.
