### ISSUE TITLE
Make cacheBust a multi task/remove hash from busted url

### ISSUE THREAD

**Issue by kappasims** [hollandben/grunt-cache-bust#80]
Two feature requests:

-Allow multiple configurations/parameters to support different scripts for different environments. For example qa scripts are not concatenated but production scripts are concatenated into one file. Cachebusting QA is sometimes a necessity.  The current workaround is to add all of the files into the configuration and let it warn when files are missing.

-Add an option for removing the grunt-cache-bust URL fragment so it doesn't show up in the links. This would be best suited for a prod-specific configuration. The current workaround is an additional grunt task to scan through the files and delete all instances of "#grunt-cache-bust".

**Comment by hollandben** [comment]
Cachebusting QA is sometimes a necessity

Your QA environment should be as close to your production environment as possible, which means running tests/QA against concatenated files.

    removing the grunt-cache-bust URL fragment so it doesn't show up in the links

Great suggestion - hadn't thought about . Have created a separate ticket for this #93

**Comment by kappasims** [comment]
We have a QA environment where we do not compile our handlebars templates into Javascript, but a staging environment where we do compile and concat as you describe. Cachebusting a nonexistent template Js file in our QA environment caused warnings due to it not being found. It may be that we should be compiling the templates in our QA environment as well though.

**Comment by hollandben** [comment]
Okey, thanks for the clarification. 

So an option such as `showRun` which is a boolean would be a good approach. That way you can check an environment variable, and if it's QA, then don't run that task. 

Sound good?

**Comment by hollandben** [comment]
Another work around within your setup would to have 2 grunt tasks; one for QA and one for everything else

**Comment by hollandben** [comment]
I've merged a change to remove the hint fragment when the task is run - #103. I shall be closing this ticket now as the environment problem is specific to your needs and not those of the task

**Comment by kappasims** [comment]
Awesome, thanks!
