### ISSUE TITLE
Filter for <use> elements doesn't work

### ISSUE THREAD

**Issue by mzgajner** [hollandben/grunt-cache-bust#82]
I'm using a SVG sprite to show icons. They are included in the markup like this:
```html
<svg>
  <use xlink:href="/images/sprite.svg#icon-arrow" />
</svg>
```
To cachebust the references to `sprite.svg`, I configured `grunt-cache-bust` by following the default filter examples:
```js
cacheBust: {
  options: {
    ...
    filters: {
      'use': function() { 
        return this.attribs['xlink:href'].split('#')[0]; 
      }
    }
  },
  ...
}
```
`grunt-cache-bust` correctly goes through my markup and busts some other stuff like JS scripts, but the `<use>` tags are left untouched. No errors (like files not being found) are reported either.

Did I make a mistake when defining my custom filter or is it something with `grunt-cache-bust`?

**Comment by mzgajner** [comment]
OK, got a bit further with this. The first problem is that [this function](https://github.com/hollandben/grunt-cache-bust/blob/master/tasks/cachebust.js#L81-L83) assumes paths can only be in `href` or `src` attributes. This can be easily solved by also adding a case with `xlink:href`.

The second problem is the `#` character in the file path (even though I tried to account for it in my filter definition) - if I remove that (and solve the aforementioned problem), it seems to work normally.

**Comment by hollandben** [comment]
Fxied in PR
