### ISSUE TITLE
Feature request: Cachebusting assets referenced in XML file

### ISSUE THREAD

**Issue by unruthless** [hollandben/grunt-cache-bust#85]
Windows 8.1 and IE 11 rely on tile pictures (aka favicons) specified in an XML file called `browserconfig.xml` that sits at a website's root. We therefore need to cachebust assets referenced in XML. (Thanks, Microsoft!)

I looked through the code and this functionality doesn't appear to exist -- please consider this a feature request.

If you'd like to take a crack at implementing asset path scraping from XML, here's an example `browserconfig.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
  <msapplication>
    <tile>
      <square70x70logo src="/mstile-70x70.png"/>
      <square150x150logo src="/mstile-150x150.png"/>
      <square310x310logo src="/mstile-310x310.png"/>
      <wide310x150logo src="/mstile-310x150.png"/>
      <TileColor>#2b5797</TileColor>
    </tile>
  </msapplication>
</browserconfig>
```

**Comment by hollandben** [comment]
Happy to include this. Marked as an enhancement. Will try to get round to it soon. Thanks.

**Comment by hollandben** [comment]
Completed in #118

**Comment by unruthless** [comment]
Looks great, thank you for implementing!
