### ISSUE TITLE
Cache busting font assets through src property

### ISSUE THREAD

**Issue by stackptr** [hollandben/grunt-cache-bust#87]
https://github.com/stackptr/grunt-cache-bust/blob/master/tasks/cachebust.js#L105

This block indicates that the only assets busted in CSS files are those referenced via the `background` and `content` properties.

In a given project I have a LESS file referencing font assets that is then compiled to a CSS file using the `src` property. As such, when the cache-bust task is run on this file, these assets are left intact.

Relatively simple fix, I wanted to check if there was a rationale behind this or if it was possibly a quirk of the LESS parser. Will send PR shortly.

**Comment by hollandben** [comment]
You are correct, it only checks the `background` and `content`. I shall change this so it's more configurable, possibly having these two as the default options with the ability to extend them with more. Thanks for bring it up

**Comment by hollandben** [comment]
Fixed in #95
