### ISSUE TITLE
Unable to cache bust more than one asset on a property

### ISSUE THREAD

**Issue by stackptr** [hollandben/grunt-cache-bust#88]
An addendum to #87 

If I have more than one value on a property, only the first value is cache busted (assuming the value is a url(...) )

**Comment by hollandben** [comment]
Can you provide an example that I could write a test around?

**Comment by stackptr** [comment]
Like the CSS that tripped this up? For example, my project defines a font-face:

@font-face {
	font-family: 'font-name';
	src:url('/style/fonts/font.eot');
	src:url('/style/fonts/font.eot') format('embedded-opentype'),
		url('/style/fonts/font.woff') format('woff'),
		url('/style/fonts/font.ttf') format('truetype'),
		url('/style/fonts/font.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}

When this is passed to the cache-bust, only the first is busted.

**Comment by hollandben** [comment]
That's great. Will get this implemented soon

**Comment by hollandben** [comment]
Fixed in #95
