### ISSUE TITLE
baseDir does not appear to be applied consistently

### ISSUE THREAD

**Issue by mbenna** [hollandben/grunt-cache-bust#91]
Ben, first of all, thanks so much for a great plugin! Much better than the other cache-bust plugins I have found.

I'm having trouble getting baseDir to work. None of the assets in the css file are being found. Here's the setup:

* current dir contains Gruntfile.js
* dist/ folder (subdir of current) contains all the public content ready to be cache busted. Everything in that folder is relative to that folder (it basically just gets copied to an html folder on a web server). All filenames are relative to index.html and none are absolute (i.e. the whole thing would work from the root of a domain or from a subdir of a domain).

Gruntfile.js

    	options: {
    		encoding: 'utf8',
    		algorithm: 'sha256',
    		length: 16,
    		baseDir: "dist/",
    		jsonOutput: 'rename-cachebuster-map.json',
    		deleteOriginals: true,
    		enableUrlFragmentHint: true,
    	},
    	assets: {
    		files: [{
    			src: [
    			      'dist/js/combined.js',
    			      'dist/index.html',
    			      'dist/css/combined*.css',
    			      ]
    		}]
    	},

If I don't specify dist/ in front of the src files it doesn't find them.
However, the stuff in the css file is not found, e.g. lots of messages like this while processing css:
`>> Static asset "images\bg-video.jpg" skipped because it wasn't found.`

And the json output:

    {
      "dist\\images\\twitter-share.png": "images\/twitter-share.b60dd3dc7e98c7ca.png",
      "dist\\images\\facebook-share.png": "images\/facebook-share.74bcb41d47f3adb0.png",
      "dist\\faq.html": "faq.9cc576831abdd69a.html",
      "dist\\team.html": "team.9b8d5c53ac8c7bd0.html",
      "dist\\js\\combined.js": "js\/combined.740066ba6ac91af5.js",
      "dist\\css\\combined.css": "css\/combined.32469c2f0ebe0f31.css",
      etc.
    }

Note the dist/ for the original and missing for the busted. Also note the mixing of forward slashes and backslashes (but I don't think that's the issue).

It would also be nice if the baseDir were auto-applied in front of the asset filenames (so it did not need to be repeated) and did not appear at all in the map json (because it doesn't relate to the distribution package at all). In other words, just prepend baseDir to all file accesses but otherwise don't use it anywhere. Does that make sense?

Is my config broken or have I run into a use case that needs a little more debugging?

Thanks for any tips!
Mike

**Comment by hollandben** [comment]
This idea of the `baseDir` option is so you can tell the task to look for your assets in a different location from the one referenced in your HTML files.

An example would be that you have a file that points to `/js/script.js`. When run on the server, this file would be served to the browser successfully. During the build (so on a normal file system) the file may exist `assets/js/script.js`. The `baseDir` option allows you to tell the task that all the assets are kept in the `assets` folder on the file system, but it keeps the path the same in HTML file.

I'm not 100% clear on your setup so maybe you could answer some questions for me.

1. What does an assets in the `dist/index.html` file look like? i.e. `/js/scripts` or `/dist/js/scripts`.
1. Is your web server running from within your `dist` folder?

**Comment by mbenna** [comment]
Thank you for clarifying. In an effort to understand and explain the problem further (and produce a repro for you), I forked and created a test case that fails: https://github.com/mbenna/grunt-cache-bust/tree/subdirpaths

If you load up test/fixtures/csssubdirreplace.html in a browser it displays just fine, but cache busting css/stylesheet.css results in:

    >> Static asset "assets\image2.jpg" skipped because it wasn't found.
    >> Static asset "assets\css-image.jpg" skipped because it wasn't found.
    >> Static asset "assets\css-image-quotes.jpg" skipped because it wasn't found.
    >> Static asset "assets\css-image-large.jpg" skipped because it wasn't found.
    >> Static asset "assets\image1.jpg" skipped because it wasn't found.
    The file tmp/css/stylesheet.css was busted!

It's now clear to me that grunt-cache-bust doesn't know the paths in test/fixtures/css/stylesheet.css should be relative to test/fixtures, but I have no idea how to fix that. Perhaps that's the per-file baseDir that just got added?
