### ISSUE TITLE
Refactor!!!!!

### ISSUE THREAD

**Issue by hollandben** [hollandben/grunt-cache-bust#94]
This task is now getting very large with a mix of domains, Need to break this up so that the task can be run via the command line and a grunt/gulp wrapper provided.

Also, the test file needs to be broken up so that it's a lot better. Probably move to use Mocha or Jasmine

**Comment by sixinli** [comment]
Hi,

I am wondering if there's a plan to add support for gulp? Would you be open to a PR if it's not already in the roadmap? It would be very nice to have it work in both grunt and gulp!

Thanks,
Sixin
