### ISSUE TITLE
Add support for framework-specific URL syntax (or ASP.NET virtual URLs) when using URL fragment?

### ISSUE THREAD

**Issue by kappasims** [hollandben/grunt-cache-bust#99]
This one is a bit of a judgment call, but here's my issue. 

I have an ASP.NET MVC application where I'm cachebusting view templates (.cshtml files) that contain links to resources. Virtual URLs (application root-specific URLs, for example if the app is being served up from a subfolder) take the following syntax in ASP.NET's Razor engine:

`<script src='@Url.Content("~/Contents/Scripts/jQuery.js#grunt-cache-bust")'></script>`

This leads to errors when I run the cachebust task--it can't find a folder named "~". I've managed to work around the issue by changing the syntax to this:

`<script src='@Url.Content("~/" + "Contents/Scripts/jQuery.js#grunt-cache-bust")'></script>`

so grunt-cache-bust only tries to bust the second half, which gives it a cwd-relative path to bust. 

If there was some way to keep from having to write the URLs this way it would be appreciated.

**Comment by hollandben** [comment]
You could always try adding `@Url.Content("~` to the `replaceTerms` option. That feature got added because I was having the same problem with a .NET MVC projects

**Comment by kappasims** [comment]
Got it. Will do!
